module.exports = listBalles = [

    // BULLES SIMPLES 
   
    { 
        id:0,
        typeName : "bubble",
        posX: -4,
        posY: 0,
        couleur: 'magenta',
        rayon: 2,
        temps: 0.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:-1,
        typeName : "bubble",
        posX: -4,
        posY: -3,
        couleur: 'red',
        rayon: 2,
        temps: 1,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:2,
        typeName : "bubble",
        posX: -4,
        posY: 3,
        couleur: 'yellow',
        rayon: 2,
        temps: 1.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:3,
        typeName : "bubble",
        posX: -4,
        posY: 0,
        couleur: 'blue',
        rayon: 2,
        temps: 2,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:4,
        typeName : "bubble",
        posX: -4,
        posY: -3,
        couleur: 'green',
        rayon: 2,
        temps: 2.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:5,
        typeName : "bubble",
        posX: 4,
        posY: 0,
        couleur: 'magenta',
        rayon: 2,
        temps: 0.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:6,
        typeName : "bubble",
        posX: 4,
        posY: -3,
        couleur: 'red',
        rayon: 2,
        temps: 1,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:7,
        typeName : "bubble",
        posX: 4,
        posY: 3,
        couleur: 'yellow',
        rayon: 2,
        temps: 1.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:8,
        typeName : "bubble",
        posX: 4,
        posY: 0,
        couleur: 'blue',
        rayon: 2,
        temps: 2,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:9,
        typeName : "bubble",
        posX: 4,
        posY: -3,
        couleur: 'green',
        rayon: 2,
        temps: 2.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    // PUZZLE
    {
        id: 10,
        typeName: "bubble",
        posX: -2.5,
        posY: 0,
        couleur: 'white',
        rayon: 2,
        temps: 3,
        type: 7,
        duration: 1.5,
        rotation: 90,
        side: 1,
        texture: ""
    },
    {
        id: 11,
        typeName: "bubble",
        posX: 2.5,
        posY: 0,
        couleur: 'white',
        rayon: 2,
        temps: 3,
        type: 7,
        duration: 1.5,
        rotation: -90,
        side: 2,
        texture: ""
    },
    {
        id: 12,
        typeName: "bubble",
        posX: 0,
        posY: 0,
        couleur: 'white',
        rayon: 2,
        temps: 3,
        type: 6,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "ciblePuzzle"
    },

    // BULLE SIMPLE - TOUCHER PROLONGER - BULLE SIMPLE
    // GAUCHE
    { 
        id:13,
        typeName : "bubble",
        posX: -4,
        posY: 2,
        couleur: 'black',
        rayon: 2,
        temps: 4.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:14,
        typeName : "bubble",
        posX: -5.5,
        posY: -2,
        idTrajectoire: 1,
        couleur: 'red',
        rayon: 1,
        temps: 5,
        type: 1,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:16,
        typeName : "bubble",
        idTrajectoire: 1,
        posX: -3,
        posY: -2,
        couleur: 'grey',
        rayon: 1,
        temps: 5,
        type: 9,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "cibleToucherProlonger"
    },
    { 
        id:15,
        idBubble : 15,
        idCible : 16,
        typeName : "trajectory",
        posX: -4,
        posY: -2,
        couleur: 'green',
        temps: 5,
        duration: 1.5, 
        width : 5,
        height : 3,
    },
    // DROITE
    { 
        id:17,
        typeName : "bubble",
        posX: 4,
        posY: 2,
        couleur: 'black',
        rayon: 2,
        temps: 4.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:18,
        typeName : "bubble",
        posX: 3,
        posY: -2,
        idTrajectoire: 1,
        couleur: 'red',
        rayon: 1,
        temps: 5,
        type: 1,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:20,
        typeName : "bubble",
        idTrajectoire: 1,
        posX: 5.5,
        posY: -2,
        couleur: 'grey',
        rayon: 1,
        temps: 5,
        type: 9,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "cibleToucherProlonger"
    },
    { 
        id:19,
        idBubble : 19,
        idCible : 20,
        typeName : "trajectory",
        posX: 4,
        posY: -2,
        couleur: 'green',
        temps: 5,
        duration: 1.5, 
        width : 5,
        height : 3,
    },

    // 2 * 2 * 2 * 2 BULLES
    // GAUCHE
    { 
        id:21,
        typeName : "bubble",
        posX: -7,
        posY: 2.75,
        couleur: 'magenta',
        rayon: 2,
        temps: 6.75,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:22,
        typeName : "bubble",
        posX: -3,
        posY: 2.75,
        couleur: 'magenta',
        rayon: 2,
        temps: 6.75,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:23,
        typeName : "bubble",
        posX: -4.5,
        posY: 0,
        couleur: 'red',
        rayon: 2,
        temps: 7.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:21,
        typeName : "bubble",
        posX: -7,
        posY: -2.75,
        couleur: 'white',
        rayon: 2,
        temps: 8,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:22,
        typeName : "bubble",
        posX: -3,
        posY: -2.75,
        couleur: 'white',
        rayon: 2,
        temps: 8,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    // DROITE
    { 
        id:23,
        typeName : "bubble",
        posX: 2.5,
        posY: 2.75,
        couleur: 'blue',
        rayon: 2,
        temps: 6.75,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:24,
        typeName : "bubble",
        posX: 2.5,
        posY: 0,
        couleur: 'green',
        rayon: 2,
        temps: 7.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:25,
        typeName : "bubble",
        posX: 2.5,
        posY: -2.75,
        couleur: 'black',
        rayon: 2,
        temps: 8,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    // DEUX PUZZLES 

    {
        id: 26,
        typeName: "bubble",
        posX: -2.5,
        posY: 2,
        couleur: 'white',
        rayon: 2,
        temps: 8.75,
        type: 7,
        duration: 1.5,
        rotation: 90,
        side: 1,
        texture: ""
    },
    {
        id: 27,
        typeName: "bubble",
        posX: 2.5,
        posY: 2,
        couleur: 'white',
        rayon: 2,
        temps: 8.75,
        type: 7,
        duration: 1.5,
        rotation: -90,
        side: 2,
        texture: ""
    },
    {
        id: 28,
        typeName: "bubble",
        posX: 0,
        posY: 2,
        couleur: 'yellow',
        rayon: 2,
        temps: 8.75,
        type: 6,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "ciblePuzzle"
    },
    {
        id: 29,
        typeName: "bubble",
        posX: -2.5,
        posY: -2,
        couleur: 'white',
        rayon: 2,
        temps: 9.5,
        type: 7,
        duration: 1.5,
        rotation: 90,
        side: 1,
        texture: ""
    },
    {
        id: 30,
        typeName: "bubble",
        posX: 2.5,
        posY: -2,
        couleur: 'white',
        rayon: 2,
        temps: 9.5,
        type: 7,
        duration: 1.5,
        rotation: -90,
        side: 2,
        texture: ""
    },
    {
        id: 31,
        typeName: "bubble",
        posX: 0,
        posY: -2,
        couleur: 'cyan',
        rayon: 2,
        temps: 9.5,
        type: 6,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "ciblePuzzle"
    },

    // TOUCHER PROLONGER + MALUS 
    { 
        id:32,
        typeName : "bubble",
        posX: 3,
        posY: 0,
        idTrajectoire: 1,
        couleur: 'magenta',
        rayon: 1,
        temps: 11,
        type: 1,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:34,
        typeName : "bubble",
        idTrajectoire: 1,
        posX: 6,
        posY: 0,
        couleur: 'grey',
        rayon: 1,
        temps: 11,
        type: 9,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "cibleToucherProlonger"
    },
    { 
        id:33,
        idBubble : 33,
        idCible : 34,
        typeName : "trajectory",
        posX: 5,
        posY: 0,
        couleur: 'blue',
        temps: 11,
        duration: 1.5, 
        width : 5,
        height : 3,
    },

    { 
        id:35,
        typeName : "bubble",
        type: 4,

        posX: -2,
        posY: 0,
        posXOpponent : 0,
        posYOpponent : 0,
        impulsion: 0.5,

        couleur: 'white',
        rayon: 2,
        temps: 11,
        duration: 1.5,
        rotation: 90,
        side: 0,
        freezeDuration : 3,
        texture: "flocon"
    },

    // TOUCHER PROLONGER + 2 BULLES
    { 
        id:36,
        typeName : "bubble",
        posX: -6.5,
        posY: 0,
        idTrajectoire: 1,
        couleur: 'magenta',
        rayon: 1,
        temps: 12.75,
        type: 1,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:38,
        typeName : "bubble",
        idTrajectoire: 1,
        posX: -3.5,
        posY: 0,
        couleur: 'grey',
        rayon: 1,
        temps: 12.75,
        type: 9,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "cibleToucherProlonger"
    },
    { 
        id:37,
        idBubble : 37,
        idCible : 38,
        typeName : "trajectory",
        posX: -5,
        posY: 0,
        couleur: 'yellow',
        temps: 12.75,
        duration: 1.5, 
        width : 5,
        height : 3,
    },
       
    { 
        id:39,
        typeName : "bubble",
        posX: 3,
        posY: 2,
        couleur: 'black',
        rayon: 2,
        temps: 12.75,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
       
    { 
        id:40,
        typeName : "bubble",
        posX: 3,
        posY: -2,
        couleur: 'black',
        rayon: 2,
        temps: 12.75,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    // 2 BULLES + PUZZLE
    { 
        id:41,
        typeName : "bubble",
        posX: 3,
        posY: 2,
        couleur: 'green',
        rayon: 2,
        temps: 14.25,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:42,
        typeName : "bubble",
        posX: -3,
        posY: 2,
        couleur: 'green',
        rayon: 2,
        temps: 14.25,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    {
        id: 43,
        typeName: "bubble",
        posX: -2.5,
        posY: -2,
        couleur: 'white',
        rayon: 2,
        temps: 14.75,
        type: 7,
        duration: 1.5,
        rotation: 90,
        side: 1,
        texture: ""
    },
    {
        id: 44,
        typeName: "bubble",
        posX: 2.5,
        posY: -2,
        couleur: 'white',
        rayon: 2,
        temps: 14.75,
        type: 7,
        duration: 1.5,
        rotation: -90,
        side: 2,
        texture: ""
    },
    {
        id: 45,
        typeName: "bubble",
        posX: 0,
        posY: -2,
        couleur: 'white',
        rayon: 2,
        temps: 14.75,
        type: 6,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "ciblePuzzle"
    },

    // 1 TOUCHER PROLONGER + MALUS MULTIPLE 
    { 
        id:46,
        typeName : "bubble",
        posX: -1.75,
        posY: 1,
        idTrajectoire: 1,
        couleur: 'red',
        rayon: 1,
        temps: 16.5,
        type: 1,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:48,
        typeName : "bubble",
        idTrajectoire: 1,
        posX: 1,
        posY: 1,
        couleur: 'grey',
        rayon: 1,
        temps: 16.5,
        type: 9,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "cibleToucherProlonger"
    },
    { 
        id:47,
        idBubble : 47,
        idCible : 48,
        typeName : "trajectory",
        posX: 0,
        posY: 1,
        couleur: 'magenta',
        temps: 16.5,
        duration: 1.5, 
        width : 5,
        height : 3,
    },
    { 
        id:49,
        typeName : "bubble",
        type: 5,
         posX: 0,
         posY: -3,
         posXOpponent : 0,
         posYOpponent : 0,
         impulsion: 0.5,

         couleur: 'green',
         rayon: 2,
         temps: 16.5,
         duration: 3,
         rotation: 90,
         side: 0,
         nbMalusMultiple : 8,
         texture: ""
     },

     // UNE BULLE 
     { 
        id:50,
        typeName : "bubble",
        posX: -3,
        posY: 2,
        couleur: 'blue',
        rayon: 2,
        temps: 18,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    // 2 * 2 BULLES 

    { 
        id:51,
        typeName : "bubble",
        posX: -3.5,
        posY: -2.75,
        couleur: 'yellow',
        rayon: 2,
        temps: 20,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:52,
        typeName : "bubble",
        posX: -2.5,
        posY: 2.75,
        couleur: 'yellow',
        rayon: 2,
        temps: 20,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:53,
        typeName : "bubble",
        posX: 2.5,
        posY: -2.75,
        couleur: 'blue',
        rayon: 2,
        temps: 20,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:54,
        typeName : "bubble",
        posX: 3.5,
        posY: 2.75,
        couleur: 'blue',
        rayon: 2,
        temps: 20,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    // 2 * 2 BULLES
    { 
        id:55,
        typeName : "bubble",
        posX: -2.5,
        posY: -2.75,
        couleur: 'white',
        rayon: 2,
        temps: 22,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:56,
        typeName : "bubble",
        posX: -3.5,
        posY: 2.75,
        couleur: 'white',
        rayon: 2,
        temps: 22,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:57,
        typeName : "bubble",
        posX: 3.5,
        posY: -2.75,
        couleur: 'green',
        rayon: 2,
        temps: 22,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    { 
        id:58,
        typeName : "bubble",
        posX: 2.5,
        posY: 2.75,
        couleur: 'green',
        rayon: 2,
        temps: 22,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },

    // PUZZLE 
    {
        id: 59,
        typeName: "bubble",
        posX: -2.5,
        posY: 0,
        couleur: 'white',
        rayon: 2,
        temps: 23.5,
        type: 7,
        duration: 1.5,
        rotation: 90,
        side: 1,
        texture: ""
    },
    {
        id: 60,
        typeName: "bubble",
        posX: 2.5,
        posY: 0,
        couleur: 'white',
        rayon: 2,
        temps: 23.5,
        type: 7,
        duration: 1.5,
        rotation: -90,
        side: 2,
        texture: ""
    },
    {
        id: 61,
        typeName: "bubble",
        posX: 0,
        posY: 0,
        couleur: 'magenta',
        rayon: 2,
        temps: 23.5,
        type: 6,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "ciblePuzzle"
    },

    // 2 + 2 BULLES
    { 
        id:62,
        typeName : "bubble",
        posX: -2.5,
        posY: -3,
        couleur: 'blue',
        rayon: 2,
        temps: 25,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:63,
        typeName : "bubble",
        posX: 2.5,
        posY: 3,
        couleur: 'blue',
        rayon: 2,
        temps: 25,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:64,
        typeName : "bubble",
        posX: -2.5,
        posY: 0,
        couleur: 'green',
        rayon: 2,
        temps: 25.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },
    { 
        id:65,
        typeName : "bubble",
        posX: 2.5,
        posY: 0,
        couleur: 'green',
        rayon: 2,
        temps: 25.5,
        type: 0,
        duration: 1.5,
        rotation: 90,
        side: 0,
        texture: "bubble2"
    },





    


   
]