module.exports = listBalles = [

    { 
        id:0,
        typeName : "bubble",
        posX: 2,
        posY: 0,
        idTrajectoire: 1,
        couleur: 'magenta',
        rayon: 1,
        temps: 0,
        type: 1,
        duration: 10,
        rotation: 90,
        side: 0,
        texture: ""
    },
    { 
        id:2,
        typeName : "bubble",
        idTrajectoire: 1,
        posX: 5,
        posY: 0,
        couleur: 'grey',
        rayon: 1,
        temps: 0,
        type: 9,
        duration: 10,
        rotation: 90,
        side: 0,
        texture: "ciblePuzzle"
    },
    { 
        id:1,
        idBubble : 1,
        idCible : 2,
        typeName : "trajectory",
        posX: 4,
        posY: 0,
        couleur: 'blue',
        temps: 0,
        duration: 10, 
        width : 5,
        height : 3,
    },
    
    { 
        id:3,
        typeName : "bubble",
        posX: 3,
        posY: 1,
        couleur: 'white',
        rayon: 3,
        temps: 0,
        type: 0,
        duration: 3,
        rotation: 90,
        side: 0,
        texture: ""
    },
    { 
        id:4,
        typeName : "bubble",
        posX: -6,
        posY: 0,
        couleur: 'white',
        rayon: 3,
        temps: 3,
        type: 7,
        duration: 3,
        rotation: 90,
        side: 1,
        texture: ""
        },
        { 
        id:5,
        typeName : "bubble",
        posX: 6,
        posY: 0,
        couleur: 'white',
        rayon: 3,
        temps: 3,
        type: 7,
        duration: 3,
        rotation: -90,
        side: 2,
        texture: ""
    },
    { 
        id:6,
        typeName : "bubble",
        posX: 0,
        posY: 0,
        couleur: 'magenta',
        rayon: 3,
        temps: 3,
        type: 6,
        duration: 3,
        rotation: 90,
        side: 0,
        texture: "ciblePuzzle"
    },

    { 
        id:7,
        typeName : "bubble",
        posX: 0,
        posY: 2,
        couleur: 'white',
        rayon: 3,
        temps: 6,
        type: 0,
        duration: 3,
        rotation: 90,
        side: 0,
        texture: ""
    },
    { 
        id:8,
        typeName : "bubble",
        posX: 0,
        posY: 0,
        couleur: 'yellow',
        rayon: 3,
        temps: 9,
        type: 0,
        duration: 3,
        rotation: 90,
        side: 0,
        texture: ""
    }
];